echo off

rem chcp 1251>nul
chcp 65001>nul

setlocal enableextensions

echo =========================================
echo НАЧАЛО СБОРКИ 

call "C:\Program Files (x86)\Embarcadero\RAD Studio\9.0\bin\rsvars.bat"

rem set MSBUILD = "c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe"
SET MSBuildPath=C:\Windows\Microsoft.NET\Framework\v4.0.30319\
SET PATH=%PATH%;%MSBuildPath%;

set configuration=%1
set extra=

set ProjectPath="%~dp0bin\%configuration%"
set BinPath="bin\%configuration%"
set TestProjectPath="%~d0\AUTOTESTS\%configuration%Console"

set ProjectGroup="%~dp0src\BuildAll.groupproj"
set TestProjectGroup="%~dp0src\ILSMonitoringTest.groupproj"


set extra=ExtraDefines=

if "%1" == "Release" (
set extra=ExtraDefines=AutoGeneratedVersion
)

if "%1" == "Feature" (
set extra=ExtraDefines=AutoGeneratedVersion
set configuration=Debug
)

echo Конфигурация сборки = %configuration% 
echo Конфигурация версии = %extra% 

echo Собираем проект %ProjectGroup% в %BinPath%

brcc32.exe lib\jcl\source\common\JclUnicode.rc
rem MSBuild.exe /t:Clean,Build /p:Config=%configuration%;%extra%DCC_ExeOutput=%BinPath% %ProjectGroup%
MSBuild.exe /t:Clean,Build /p:Config=%configuration%;%extra%  %ProjectGroup%

if NOT "%ERRORLEVEL%" == "0" (
  echo Сборка конфигурации завершена с ERRORLEVEL = %ERRORLEVEL%	
  exit /b -1
)
echo Сборка проекта завершена
echo --------------------------------------------

echo Удаляем служебные файлы
del "%BinPath%\*.drc"
del "%BinPath%\*.map"
del "%ProjectPath%\*.drc"
del "%ProjectPath%\*.map"
del "%TestProjectPath%\*.drc"
del "%TestProjectPath%\*.map"

exit /b 0

echo ЗАВЕРШЕНИЕ СБОРКИ

echo ==================================================
endlocal
